import Tab from './components/Tab'
import Tags from './components/Tags'

const rawTags = [
  'html',
  'css',
  'javascript',
  'database',
  'php',
  'ruby',
  'design',
  'java',
  'tool',
  'bebas',
  'android',
  'hosting',
  'wordpress',
  'codeigniter',
  'laravel',
  'jquery',
  'nodejs',
  'vue',
  'angular',
  'mobile',
  'api',
  'ajax',
  'python',
  'game',
  'c',
  'c++',
  'swift',
  'ios',
  'objective-c',
  'seo',
  'website',
  'tips-dan-trik',
  'slim',
  'sharing',
  'linux',
  'UX',
  'testing',
  'firebase',
  'responsive',
  'progressive-web-app',
  'flask',
  'django',
  'data-science',
  'reactjs',
  'nuxtjs',
  'vuex',
  'react-native',
  'redux',
  'nextjs',
  'mysql',
  'mongodb',
  'graphql',
  'gatsbyjs',
  'go',
  'flutter',
  'nativescript',
  'kotlin',
  'sqlite',
  'karir',
  'produktivitas',
  'server',
  'windows',
  'mac',
  'AWS',
  'hugo',
  'machine-learning',
  'artificial-intelligence',
  'menulis',
  'softskill',
  'remote',
  'opensource',
  'algoritma',
  'dokumentasi',
  'rust',
  'typescript',
  'text-editor',
  'belajar',
  'security',
  'motivasi',
  'matematika',
  'static-site',
  'snippet',
  'Alpinejs',
  'Lumen',
  'Deno',
  'wawancara',
  'komunitas',
  'startup',
  'inspirasi',
  'keragaman',
  'git',
  'tailwindcss',
  'laravel-livewire',
  'inertiajs',
  'dart',
  'serverless',
  'struktur-data',
  'analisis',
  'fastAPI',
  'karya',
]

export default function ForumLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-3 xl:flex-row">
      <div className="pt-3 xl:flex-1 xl:py-3">
        <Tab />
        <>{children}</>
      </div>
      <Tags tags={rawTags} />
    </div>
  )
}
